algoritmo "CONVERSOR DOLAR"
// Função :
// Autor :
// Data : 11/06/2024
// Seção de Declarações 
var
   reais, dolar, conver: real
inicio

      Escreval ("Hm vamos viajar, mas iremos precisar de dolar´s bb.")
      Escreval ("Quanto temos em reais?")
      leia (reais)
      Escreval ("Qual a cotação do dolar hoje?")
      leia (dolar)
      conver <- reais / dolar
      Escreval ("Hm temos US$", conver, " dolares acho que dá para viajarmos de boas")
fimalgoritmo
