algoritmo "04 - Anterior e sucessor"
// Função : 4 - Faça um algoritmo que receba um número inteiro e imprima na tela o seu antecessor e o seu sucessor.
// Autor :
// Data : 11/08/2024
// Seção de Declarações 
var
  p, s, t : inteiro
inicio

      Escreva ("Digite um numero:")
      leia (p)
      s <- (p - 1 )
      t <- (p + 1)
      Escreval (s, p, t)
      Escreval ("O número digitado foi:", p)
      Escreval ("O seu antecessor, ", s)
      Escreval ("Seu Posterior, ", t)

fimalgoritmo
